export enum ObjectType {
    CUBE = 'CUBE',
    TETRAHEDRON = 'TETRAHEDRON',
    OCTAHEDRON = 'OCTAHEDRON',
    DODECAHEDRON = 'DODACEHEDRON',
    ICOSAHEDRON = 'ICOSAHEDRON',
    TETROMINO = 'TETROMINO',
}